version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongo_prod
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data_prod:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_prod
    restart: always
    ports:
      - "${BACKEND_PORT}:3000"
    env_file: .env
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin
      NODE_ENV: production
    depends_on:
      - mongo

volumes:
  mongo_data_prod:
