version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongo_prod
    restart: always
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data_prod:/data/db
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_prod
    restart: always
    ports:
      - '${BACKEND_PORT}:3000'
      - '5001:5001'
      - '5002:5002'
    env_file: .env
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin
      NODE_ENV: production
      AI_SERVICE_URL: http://localhost:5001
      CHATBOT_SERVICE_URL: http://localhost:5002
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge